version: '3'
services:
  sensor-bot:
    image: fininimini/scratch-view-bot:py
    container_name: Scratch-View-Bot
    restart: unless-stopped
    environment:
      mongodb_url: Change to your own mongodb url
      name: Change to your own chosen name for the worker